### ISSUE TITLE
Parse xsd:integer to int

### ISSUE THREAD

**Issue by angelo-v** [rdfjs-base/serializer-jsonld#4]
An object with datatype xsd:integer should be serialized as a native JavaScript integer in JSON-LD.

## Input

```
_:c14n0 <ex:value> "42"^^<http://www.w3.org/2001/XMLSchema#integer> .
```

## Actual output

```json
{
  "ex:value": {
    "@value": "42",
    "@type": "http://www.w3.org/2001/XMLSchema#integer"
  }
}
```
## Expected output

```json
{
  "ex:value": 42
}
```

**Comment by vhf** [comment]
Hey, I don't know a lot about jsonld but I'm curious about this particular issue. JSON data types is a subset of JavaScript data types, and JavaScript does not have an integer data type.

Is representing integers as numbers semantically correct? I spent a few minutes in the jsonld spec but couldn't find evidence either way.

My concern is the confusion between integers and JSON's numbers. I noticed some jsonld parsers consider `42.0` to be an integer so you proposal could well be fine and I missed the spot in the spec?

**Comment by angelo-v** [comment]
> A JSON-LD value is [...] a number (numbers with a non-zero fractional part, i.e., the result of a modulo‑1 operation, or which are too large to represent as integers [...], are interpreted as typed values with type xsd:double, all other numbers are interpreted as typed values with type xsd:integer), 

So serializing xsd:integers as JavaScript numbers should be correct, as long as the resulting number would be interpreted as xsd:integers the other way arround.
